system: telephony: Remove Datastatusnotification.
Fix for missing qcrilhook class

D AndroidRuntime: Shutting down VM
E AndroidRuntime: FATAL EXCEPTION: main
E AndroidRuntime: Process: com.android.phone, PID: 2643
E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/qualcomm/qcrilhook/QcRilHookCallback;
E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateService(AppComponentFactory.java:129)
E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:4474)
E AndroidRuntime: 	at android.app.ActivityThread.access$1700(ActivityThread.java:248)
E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2077)
E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7883)
E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)
E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: com.qualcomm.qcrilhook.QcRilHookCallback
E AndroidRuntime: 	... 12 more

Change-Id: I9a029e0c35ceb0f6e188e3ca1ca99721673172ac